<?php
return [
    'home_page_path'                => '/images/home_page',
    'visitor_images'                => '/images/visitor_images',
    'member_images'                 => '/images/member_images',
    'customer_images'               => '/images/customer',
    'graphic_images'                => '/images/graphic_images',
    'banner_member_images'          => '/images/member_banner_images/',
    'emp_master_files'              => '/images/employee_master_files',
    'emp_master_qr_code'            => '/images/employee_master_files/emp_master_qr_code/',
    'gallary_page_path'             => '/images/gallary_page',
    'gallary_page_path_compress'    => '/images/gallary_page/gallary_page_path_compress',
    'markets_files'                 => '/images/market_images',
    'product_files'                 => '/images/product_images',
    'location_files'                => '/images/location_images',
    'mastersetting'                 => '/images/mastersetting',
    'logo_pack_files'               => '/images/logo_pack_files',
    'company_logo'                  => '/images/company_logo',
    'reports'                       => '/reports/',
    'product'                       => '/product/',
    'services'                       => '/services/',
    'media_files'                       => '/media_files/',
    'emp_document'                       => '/emp_document/',
    'attachment'                       => '/attachment/',
    'backup_file'                   => '/knok_knok/',
    'STATUS'                        => ['1'  => 'Active', '0' => 'Inactive'],
    'TRANS_STATUS'                  => ['1'  => 'CREDIT', '2' => 'DEBIT'],
    'FEATURE_TYPE'                  => [
        '1'  => 'Basic Feature',
        '2'  => 'Dashboard Feature',
        '3'  => 'Mobile App',
        // '3'  =>'Gatekeeper App Feature',
        // '4'  =>'Employee App Feature',
        // '4'  =>'Admin App Feature',
    ],
    'FORM_TYPE'                    => [
        '1'  => 'Visitor Form',
        '2'  => 'Employee Form',
        '3'  => 'Material Form',
        '4'  => 'Meeting Room',
        '5'  => 'Custom Form',
        '6'  => 'Petrolling Form',
        '6'  => 'Others',
    ],
    'CAMERA_TYPE'                   => [
        '1'  => 'Front',
        '2'  => 'Back',
    ],
    'CAMERAS_TYPE'                   => [
        '1'  => 'Camera',
        '2'  => 'Camera Timer',
    ],
    'DROPDOWN_MASTER'               => [
        '1'  => 'Employee Master',
        '2'  => 'Designation Master',
        '3'  => 'Vendor Master',
    ],
    'FORM_GROUP_TABLE'              => [
        '1'  => 'Text Box',
        '2'  => 'Number Box',
        '3'  => 'Drop Down',
        '4'  => 'Text Area',
    ],

    'CUSTOM_FORM_TYPE'              => [
        '1'  => 'Text Box',
        '2'  => 'Number Box',
        '3'  => 'QR Code',
        '4'  => 'Text Area',
        '5'  => 'Drop Down',
        '6'  => 'Camera',
        '7'  => 'Drop Down - Master',
        '8'  => 'Date Time Selection',
        '9' => 'Check Box',
        '10' => 'Boolen',
        '11' => 'Boolen - Sub - Form',
        '12' => 'Form Group Table',
        '13' => 'Mobile Otp',
    ],
    'FEATURE'                       => [
        '1'  => 'Visitor',
        '2'  => 'Employee',
        '3'  => 'Material',
        '4'  => 'Form Desk',
        '5'  => 'Meeting Room',
        '6'  => 'Petrolling',
    ],
    'FEATURE2'                       => [
        '1'  => 'Vistor Data',
        '2'  => 'Employee Data',
        '3'  => 'Material Data',
        '4'  => 'Meeting Room Data',
        '5'  => 'Petrolling Data',
        '6'  => 'Custome Form Data',
        '7'  => 'Employee Master',
        '9'  => 'Vendor Master',
        '10'  => 'GateKeeper Master',
        '11'  => 'Report',
    ],
    'FEATURE3'                       => [
        '1'  => 'Vistor',
        '2'  => 'Employee',
        '3'  => 'Material',
        '4'  => 'Meeting Room',
        '5'  => 'Patrolling',
        '6'  => 'Request'
    ],
    'FEATURE4'                       => [
        '1'  => 'Vistor',
        '2'  => 'Employee',
        '3'  => 'Material',
        '4'  => 'Meeting Room',
        '5'  => 'Patrolling',
        '6'  => 'Request',
        '7'  => 'Custome Form Data',
        '8'  => 'Employee Master',
        '9'  => 'Vendor Master',
        '10'  => 'GateKeeper Master',
        '11'  => 'Report',
    ],
    'App_Colors'                      => [
        'red'    => 'Red',
        'orange' => 'Orange',
        'green'  => 'Green',
        'blue'   => 'Blue',
        'mint'   => 'Mint',
        'yellow' => 'Yellow',
        'magenta' => 'Magenta',
        'brown'  => 'Brown',
    ],
    'Y_N_STATUS'                    => ['0'  => 'No', '1' => 'Yes'],
    'Mandatry_filed'                => '&nbsp;<span class="text-danger">*</span>',
    'ACCOUNT_TYPE'                  => ['1'  => 'Loan', '2' => 'Saving'],
    'LOAN_TYPE'                     => ['1'  => 'Monthly', '2' => 'Daily'],
    'INVESTOR_TYPE'                 => ['1'  => 'IN', '2' => 'OUT'],
    'PAYMENT_TYPE'                  => ['1'  => 'Percent (%)', '2' => 'Amt'],
    'MAIL_PORT'                    => ['1'  => '465', '2' => '587'],
    'MAIL_ENC'                     => ['1'  => 'ssl', '2' => 'tls'],
    'MAIL_TYPE'                    => ['1'  => 'Sendmail', '2' => 'SMTP', '3' => 'Mailgun', '4' => 'Sendgrid'],
    'EVENT_FOR_TYPE'               => ['1'  => 'Visitor', '2' => 'Standard Exhibitor', '3' => 'Commercial Exhibitor'],
    'Master_DATA'                  => ['1'=>'Document Type'],
    'CLIENT_TYPE'                  => ['1'  => 'Unpaid', '2' => 'Paid'],
    'ASSIGN_STATUS'                  => ['1'  => 'OPEN', '2' => 'CLOSE'],
    'ADMIN_TYPE'                  => ['1'  => 'Admin', '2' => 'Operation', '3' => 'Recruiter '],
    'EXPORT_TYPE'                 => ['1'  => 'Master Employee'],
    'EVENT_STATUS'                  => [
        '1'   => 'EVENT OFFLINE',
        '2'   => 'EVENT LIVE, BUT INVISIBLE',
        '3'   => 'EVENT LIVE',
        '4'   => 'EVENT LIVE, BUT NOT BOOKABLE',
        '5'   => 'EVENT BOOKED OUT'
    ],
    'EVENT_TAX_TYPE'                => ['1'  => 'INCLUDED', '2' => 'EXCLUDED'],
    'DISCOUNT_TYPE'                 => ['1'  => 'AMOUNT', '2' => 'PERCENTAGE'],

    'PRODUCT_TYPE'                  => [
        '1'  => 'Input',
        '2'  => 'Checkbox',
        '3'  => 'Radio button',
        '4'  => 'Textarea',
        '5'  => 'Upload',
    ],
    'REQUEST_TYPE'                  => ['1'  => 'Block', '2' => 'Request'],
    'REQUEST_GUEST_TYPE'            => ['1'  => 'Vendor', '2' => 'Visitor'],
    'LOGIN_TYPE'                    => ['1'  => 'Employee', '2' => 'Reception'],
    'sms_api_key'                   => 'SXdEwdTqbUaFBnZanftQsA',
    'sms_sender_id'                 => 'THRGSA',
    'sms_user'                      => 'katapult',
    'sms_password'                  => 'Team@HR1',
    'sms_channel'                   => 'Trans',
    'sms_route'                     => '47',
    'sms_DCS'                       => '0',
    'sms_flashsms'                  => '0',
    'sms_DLTTemplateId'             => '1307168190032069574',
    'sms_PEID'                      => '1301161797603717689',
    'GENDER'                        => ['Men' => 'Men (पुरुष)', 'Women' => 'Women (महिला)', 'Transgender' => 'Transgender (तिश्त्रीय पंथी)'],
    'STATES' => [
        // States
        'Andhra Pradesh',
        'Arunachal Pradesh',
        'Assam',
        'Bihar',
        'Chhattisgarh',
        'Goa',
        'Gujarat',
        'Haryana',
        'Himachal Pradesh',
        'Jharkhand',
        'Karnataka',
        'Kerala',
        'Madhya Pradesh',
        'Maharashtra',
        'Manipur',
        'Meghalaya',
        'Mizoram',
        'Nagaland',
        'Odisha',
        'Punjab',
        'Rajasthan',
        'Sikkim',
        'Tamil Nadu',
        'Telangana',
        'Tripura',
        'Uttar Pradesh',
        'Uttarakhand',
        'West Bengal',

        // Union Territories
        'Andaman and Nicobar Islands',
        'Chandigarh',
        'Dadra and Nagar Haveli and Daman and Diu',
        'Delhi',
        'Lakshadweep',
        'Puducherry',
        'Jammu and Kashmir',
        'Ladakh'
    ]


    ];
